#FROM ollama/ollama:0.11.8
FROM ollama/ollama:latest
WORKDIR /app
RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*
COPY ./scripts/ scripts/
RUN chmod +x scripts/start_ollama.sh

ARG MODEL_NAME="qwen3:8b"
ARG EMBD_MODEL_NAME="dengcao/Qwen3-Embedding-0.6B:Q8_0"

ENV MODEL_NAME=${MODEL_NAME}
ENV EMBD_MODEL_NAME=${EMBD_MODEL_NAME}

ENTRYPOINT [ "/app/scripts/start_ollama.sh" ]

