# start from base image
FROM python:3.11-slim
# setup working direcory ( i.e a folder inside my container where)
WORKDIR /app
# upgrade pip
RUN pip install --upgrade pip
# copy special linux dependency list and install them
COPY requirements-docker.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

### copy folders
COPY building_rag/ /app/building_rag
COPY scripts/ /app/scripts
COPY templates/ /app/templates
COPY utils/ /app/utils

# copy files
COPY README.md .
COPY app.py .
COPY chat_interface.py .
COPY chat_rag.py .
COPY data_collator.py .
COPY reranker.py .
COPY process_data.py .

