services:

  data_processing:
    build:
      context: .
      dockerfile: Dockerfile.rag
    image: ragchatbot:light 
    container_name: process_data_container
    volumes:
      - './test_data:/app/test_data'
      - ./.chroma_db-test:/app/.chroma_db-test
      - './:/app'
    depends_on:
      - ollama
    command: python process_data.py --source both --data_dir_path test_data --embed_model dengcao/Qwen3-Embedding-0.6B:Q8_0
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

  chatbot:
    image : "image: ragchatbot:light "
    container_name:  "rag_chatbot_container"
    ports:
      - "8000:8000"
    volumes:
      - ./.chroma_db:/app/.chroma_db
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - LLAMACPP_BASE_URL=http://host.docker.internal:10000
    tty: true
  ollama:
    image: ollama:latest
    