FROM ollama/ollama:latest
WORKDIR /app
RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*
COPY ./scripts/ scripts/
RUN chmod +x scripts/start_ollama.sh
ENTRYPOINT [ "/app/scripts/start_ollama.sh" ]

