services:
  ollama:
    image: ragmodels/ollama:latest
    container_name: ollama_container
    volumes:
      - ./ollama_models:/root/.ollama/models
      - ./scripts:/app/scripts
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_DEBUG=0
    ports:
      - "11434:11434"
  

  llama_cpp:
    image: reranker/llamacpp 
    container_name: llama_cpp_container
    volumes:
      - ./models:/app/models  # Maps your local ./models directory to /models in container
    ports:
      - "10000:10000"  # Using your specified port 10000
    ### custom scripts handles servert start

  my_service:
    image: rag_chatbot:light
    container_name: rag_chatbot_container
    ports:
      - "8000:8000"
    volumes:
      - ./.chroma_db:/app/.chroma_db
      - ./:/app
    environment:
    # use docker service names as URLS
    - OLLAMA_BASE_URL=http://ollama:11434
    - LLAMACPP_BASE_URL=http://llama_cpp:10000  # Access llama.cpp server
    depends_on:
      - ollama
      - llama_cpp
    tty: true
    
